/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.kobos.view;

/**
 *
 * @author guest01
 */
public class JanelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form JanelaPrincipal
     */
    public JanelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btAutor = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        mNovo = new javax.swing.JMenu();
        mCadastro = new javax.swing.JMenu();
        miAutor = new javax.swing.JMenuItem();
        mRelatorios = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));

        jToolBar1.setRollover(true);

        btAutor.setText("Autor");
        btAutor.setFocusable(false);
        btAutor.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btAutor.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAutorActionPerformed(evt);
            }
        });
        jToolBar1.add(btAutor);

        mNovo.setText("Novo");

        mCadastro.setText("Cadastro");

        miAutor.setText("Autor");
        mCadastro.add(miAutor);

        mNovo.add(mCadastro);

        jMenuBar1.add(mNovo);

        mRelatorios.setText("Relatórios");
        jMenuBar1.add(mRelatorios);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 554, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAutorActionPerformed
        AutorListaGUI al = new AutorListaGUI();
        al.setLocationRelativeTo(null);
        al.setVisible(true);
    }//GEN-LAST:event_btAutorActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAutor;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenu mCadastro;
    private javax.swing.JMenu mNovo;
    private javax.swing.JMenu mRelatorios;
    private javax.swing.JMenuItem miAutor;
    // End of variables declaration//GEN-END:variables
}
