/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.kobos.view;

import br.com.kobos.controller.FuncionarioController;
import br.com.kobos.controller.UsuarioController;
import javax.swing.JOptionPane;

/**
 *
 * @author guest01
 */
public class JanelaLogin extends javax.swing.JFrame {

    /**
     * Creates new form JanelaLogin
     */
    public JanelaLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btEntrar = new javax.swing.JButton();
        txUsuario = new javax.swing.JTextField();
        txSenha = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Usuário:");
        jLabel1.setBounds(110, 40, 60, 14);
        jDesktopPane1.add(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel2.setText("Senha:");
        jLabel2.setBounds(110, 90, 70, 14);
        jDesktopPane1.add(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        btEntrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Actions-dialog-ok-apply-icon.png"))); // NOI18N
        btEntrar.setToolTipText("Entrar");
        btEntrar.setContentAreaFilled(false);
        btEntrar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEntrarActionPerformed(evt);
            }
        });
        btEntrar.setBounds(270, 110, 50, 30);
        jDesktopPane1.add(btEntrar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        txUsuario.setBounds(110, 60, 150, 30);
        jDesktopPane1.add(txUsuario, javax.swing.JLayeredPane.DEFAULT_LAYER);
        txSenha.setBounds(110, 110, 150, 30);
        jDesktopPane1.add(txSenha, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagensBg/telaLogin.png"))); // NOI18N
        jLabel4.setBounds(0, 0, 394, 200);
        jDesktopPane1.add(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEntrarActionPerformed
        validaUsuario();
    }//GEN-LAST:event_btEntrarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btEntrar;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txSenha;
    private javax.swing.JTextField txUsuario;
    // End of variables declaration//GEN-END:variables
    
    public void validaUsuario() {
        UsuarioController uc = new UsuarioController();
        JanelaPrincipal jp = new JanelaPrincipal();
        
        String login = txUsuario.getText();
        String senha = txSenha.getText();
        
        boolean resposta = uc.ValidaUsuario(senha, senha);
        
        if(resposta == true){
            jp.setVisible(true);
            this.dispose();
        } else if (txSenha.getText().equals("") || txUsuario.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Todos os campos precisam ser preenchidos!");
        }
    }
}

